package com.digits.sdk.android;

import b.a.a.a.a.c.a;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;

final class aj
  extends a<Void, Void, List<ah>>
{
  private final ak a;
  
  public aj(ak paramak)
  {
    this.a = paramak;
  }
  
  protected List<ah> a(Void... paramVarArgs)
  {
    paramVarArgs = new ArrayList(291);
    paramVarArgs.add(new ah(new Locale("", "AF").getDisplayCountry(), 93));
    paramVarArgs.add(new ah(new Locale("", "AX").getDisplayCountry(), 358));
    paramVarArgs.add(new ah(new Locale("", "AL").getDisplayCountry(), 355));
    paramVarArgs.add(new ah(new Locale("", "DZ").getDisplayCountry(), 213));
    paramVarArgs.add(new ah(new Locale("", "AS").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "AD").getDisplayCountry(), 376));
    paramVarArgs.add(new ah(new Locale("", "AO").getDisplayCountry(), 244));
    paramVarArgs.add(new ah(new Locale("", "AI").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "AG").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "AR").getDisplayCountry(), 54));
    paramVarArgs.add(new ah(new Locale("", "AM").getDisplayCountry(), 374));
    paramVarArgs.add(new ah(new Locale("", "AW").getDisplayCountry(), 297));
    paramVarArgs.add(new ah(new Locale("", "AC").getDisplayCountry(), 247));
    paramVarArgs.add(new ah(new Locale("", "AU").getDisplayCountry(), 61));
    paramVarArgs.add(new ah(new Locale("", "AT").getDisplayCountry(), 43));
    paramVarArgs.add(new ah(new Locale("", "AZ").getDisplayCountry(), 994));
    paramVarArgs.add(new ah(new Locale("", "BS").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "BH").getDisplayCountry(), 973));
    paramVarArgs.add(new ah(new Locale("", "BD").getDisplayCountry(), 880));
    paramVarArgs.add(new ah(new Locale("", "BB").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "BY").getDisplayCountry(), 375));
    paramVarArgs.add(new ah(new Locale("", "BE").getDisplayCountry(), 32));
    paramVarArgs.add(new ah(new Locale("", "BZ").getDisplayCountry(), 501));
    paramVarArgs.add(new ah(new Locale("", "BJ").getDisplayCountry(), 229));
    paramVarArgs.add(new ah(new Locale("", "BM").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "BT").getDisplayCountry(), 975));
    paramVarArgs.add(new ah(new Locale("", "BO").getDisplayCountry(), 591));
    paramVarArgs.add(new ah(new Locale("", "BA").getDisplayCountry(), 387));
    paramVarArgs.add(new ah(new Locale("", "BW").getDisplayCountry(), 267));
    paramVarArgs.add(new ah(new Locale("", "BR").getDisplayCountry(), 55));
    paramVarArgs.add(new ah(new Locale("", "IO").getDisplayCountry(), 246));
    paramVarArgs.add(new ah(new Locale("", "VG").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "BN").getDisplayCountry(), 673));
    paramVarArgs.add(new ah(new Locale("", "BG").getDisplayCountry(), 359));
    paramVarArgs.add(new ah(new Locale("", "BF").getDisplayCountry(), 226));
    paramVarArgs.add(new ah(new Locale("", "BI").getDisplayCountry(), 257));
    paramVarArgs.add(new ah(new Locale("", "KH").getDisplayCountry(), 855));
    paramVarArgs.add(new ah(new Locale("", "CM").getDisplayCountry(), 237));
    paramVarArgs.add(new ah(new Locale("", "CA").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "CV").getDisplayCountry(), 238));
    paramVarArgs.add(new ah(new Locale("", "BQ").getDisplayCountry(), 599));
    paramVarArgs.add(new ah(new Locale("", "KY").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "CF").getDisplayCountry(), 236));
    paramVarArgs.add(new ah(new Locale("", "TD").getDisplayCountry(), 235));
    paramVarArgs.add(new ah(new Locale("", "CL").getDisplayCountry(), 56));
    paramVarArgs.add(new ah(new Locale("", "CN").getDisplayCountry(), 86));
    paramVarArgs.add(new ah(new Locale("", "CX").getDisplayCountry(), 61));
    paramVarArgs.add(new ah(new Locale("", "CC").getDisplayCountry(), 61));
    paramVarArgs.add(new ah(new Locale("", "CO").getDisplayCountry(), 57));
    paramVarArgs.add(new ah(new Locale("", "KM").getDisplayCountry(), 269));
    paramVarArgs.add(new ah(new Locale("", "CD").getDisplayCountry(), 243));
    paramVarArgs.add(new ah(new Locale("", "CG").getDisplayCountry(), 242));
    paramVarArgs.add(new ah(new Locale("", "CK").getDisplayCountry(), 682));
    paramVarArgs.add(new ah(new Locale("", "CR").getDisplayCountry(), 506));
    paramVarArgs.add(new ah(new Locale("", "CI").getDisplayCountry(), 225));
    paramVarArgs.add(new ah(new Locale("", "HR").getDisplayCountry(), 385));
    paramVarArgs.add(new ah(new Locale("", "CU").getDisplayCountry(), 53));
    paramVarArgs.add(new ah(new Locale("", "CW").getDisplayCountry(), 599));
    paramVarArgs.add(new ah(new Locale("", "CY").getDisplayCountry(), 357));
    paramVarArgs.add(new ah(new Locale("", "CZ").getDisplayCountry(), 420));
    paramVarArgs.add(new ah(new Locale("", "DK").getDisplayCountry(), 45));
    paramVarArgs.add(new ah(new Locale("", "DJ").getDisplayCountry(), 253));
    paramVarArgs.add(new ah(new Locale("", "DM").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "DO").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "TL").getDisplayCountry(), 670));
    paramVarArgs.add(new ah(new Locale("", "EC").getDisplayCountry(), 593));
    paramVarArgs.add(new ah(new Locale("", "EG").getDisplayCountry(), 20));
    paramVarArgs.add(new ah(new Locale("", "SV").getDisplayCountry(), 503));
    paramVarArgs.add(new ah(new Locale("", "GQ").getDisplayCountry(), 240));
    paramVarArgs.add(new ah(new Locale("", "ER").getDisplayCountry(), 291));
    paramVarArgs.add(new ah(new Locale("", "EE").getDisplayCountry(), 372));
    paramVarArgs.add(new ah(new Locale("", "ET").getDisplayCountry(), 251));
    paramVarArgs.add(new ah(new Locale("", "FK").getDisplayCountry(), 500));
    paramVarArgs.add(new ah(new Locale("", "FO").getDisplayCountry(), 298));
    paramVarArgs.add(new ah(new Locale("", "FJ").getDisplayCountry(), 679));
    paramVarArgs.add(new ah(new Locale("", "FI").getDisplayCountry(), 358));
    paramVarArgs.add(new ah(new Locale("", "FR").getDisplayCountry(), 33));
    paramVarArgs.add(new ah(new Locale("", "GF").getDisplayCountry(), 594));
    paramVarArgs.add(new ah(new Locale("", "PF").getDisplayCountry(), 689));
    paramVarArgs.add(new ah(new Locale("", "GA").getDisplayCountry(), 241));
    paramVarArgs.add(new ah(new Locale("", "GM").getDisplayCountry(), 220));
    paramVarArgs.add(new ah(new Locale("", "GE").getDisplayCountry(), 995));
    paramVarArgs.add(new ah(new Locale("", "DE").getDisplayCountry(), 49));
    paramVarArgs.add(new ah(new Locale("", "GH").getDisplayCountry(), 233));
    paramVarArgs.add(new ah(new Locale("", "GI").getDisplayCountry(), 350));
    paramVarArgs.add(new ah(new Locale("", "GR").getDisplayCountry(), 30));
    paramVarArgs.add(new ah(new Locale("", "GL").getDisplayCountry(), 299));
    paramVarArgs.add(new ah(new Locale("", "GD").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "GP").getDisplayCountry(), 590));
    paramVarArgs.add(new ah(new Locale("", "GU").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "GT").getDisplayCountry(), 502));
    paramVarArgs.add(new ah(new Locale("", "GG").getDisplayCountry(), 44));
    paramVarArgs.add(new ah(new Locale("", "GN").getDisplayCountry(), 224));
    paramVarArgs.add(new ah(new Locale("", "GW").getDisplayCountry(), 245));
    paramVarArgs.add(new ah(new Locale("", "GY").getDisplayCountry(), 592));
    paramVarArgs.add(new ah(new Locale("", "HT").getDisplayCountry(), 509));
    paramVarArgs.add(new ah(new Locale("", "HM").getDisplayCountry(), 672));
    paramVarArgs.add(new ah(new Locale("", "HN").getDisplayCountry(), 504));
    paramVarArgs.add(new ah(new Locale("", "HK").getDisplayCountry(), 852));
    paramVarArgs.add(new ah(new Locale("", "HU").getDisplayCountry(), 36));
    paramVarArgs.add(new ah(new Locale("", "IS").getDisplayCountry(), 354));
    paramVarArgs.add(new ah(new Locale("", "IN").getDisplayCountry(), 91));
    paramVarArgs.add(new ah(new Locale("", "ID").getDisplayCountry(), 62));
    paramVarArgs.add(new ah(new Locale("", "IR").getDisplayCountry(), 98));
    paramVarArgs.add(new ah(new Locale("", "IQ").getDisplayCountry(), 964));
    paramVarArgs.add(new ah(new Locale("", "IE").getDisplayCountry(), 353));
    paramVarArgs.add(new ah(new Locale("", "IM").getDisplayCountry(), 44));
    paramVarArgs.add(new ah(new Locale("", "IL").getDisplayCountry(), 972));
    paramVarArgs.add(new ah(new Locale("", "IT").getDisplayCountry(), 39));
    paramVarArgs.add(new ah(new Locale("", "JM").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "JP").getDisplayCountry(), 81));
    paramVarArgs.add(new ah(new Locale("", "JE").getDisplayCountry(), 44));
    paramVarArgs.add(new ah(new Locale("", "JO").getDisplayCountry(), 962));
    paramVarArgs.add(new ah(new Locale("", "KZ").getDisplayCountry(), 7));
    paramVarArgs.add(new ah(new Locale("", "KE").getDisplayCountry(), 254));
    paramVarArgs.add(new ah(new Locale("", "KI").getDisplayCountry(), 686));
    paramVarArgs.add(new ah(new Locale("", "XK").getDisplayCountry(), 381));
    paramVarArgs.add(new ah(new Locale("", "KW").getDisplayCountry(), 965));
    paramVarArgs.add(new ah(new Locale("", "KG").getDisplayCountry(), 996));
    paramVarArgs.add(new ah(new Locale("", "LA").getDisplayCountry(), 856));
    paramVarArgs.add(new ah(new Locale("", "LV").getDisplayCountry(), 371));
    paramVarArgs.add(new ah(new Locale("", "LB").getDisplayCountry(), 961));
    paramVarArgs.add(new ah(new Locale("", "LS").getDisplayCountry(), 266));
    paramVarArgs.add(new ah(new Locale("", "LR").getDisplayCountry(), 231));
    paramVarArgs.add(new ah(new Locale("", "LY").getDisplayCountry(), 218));
    paramVarArgs.add(new ah(new Locale("", "LI").getDisplayCountry(), 423));
    paramVarArgs.add(new ah(new Locale("", "LT").getDisplayCountry(), 370));
    paramVarArgs.add(new ah(new Locale("", "LU").getDisplayCountry(), 352));
    paramVarArgs.add(new ah(new Locale("", "MO").getDisplayCountry(), 853));
    paramVarArgs.add(new ah(new Locale("", "MK").getDisplayCountry(), 389));
    paramVarArgs.add(new ah(new Locale("", "MG").getDisplayCountry(), 261));
    paramVarArgs.add(new ah(new Locale("", "MW").getDisplayCountry(), 265));
    paramVarArgs.add(new ah(new Locale("", "MY").getDisplayCountry(), 60));
    paramVarArgs.add(new ah(new Locale("", "MV").getDisplayCountry(), 960));
    paramVarArgs.add(new ah(new Locale("", "ML").getDisplayCountry(), 223));
    paramVarArgs.add(new ah(new Locale("", "MT").getDisplayCountry(), 356));
    paramVarArgs.add(new ah(new Locale("", "MH").getDisplayCountry(), 692));
    paramVarArgs.add(new ah(new Locale("", "MQ").getDisplayCountry(), 596));
    paramVarArgs.add(new ah(new Locale("", "MR").getDisplayCountry(), 222));
    paramVarArgs.add(new ah(new Locale("", "MU").getDisplayCountry(), 230));
    paramVarArgs.add(new ah(new Locale("", "YT").getDisplayCountry(), 262));
    paramVarArgs.add(new ah(new Locale("", "MX").getDisplayCountry(), 52));
    paramVarArgs.add(new ah(new Locale("", "FM").getDisplayCountry(), 691));
    paramVarArgs.add(new ah(new Locale("", "MD").getDisplayCountry(), 373));
    paramVarArgs.add(new ah(new Locale("", "MC").getDisplayCountry(), 377));
    paramVarArgs.add(new ah(new Locale("", "MN").getDisplayCountry(), 976));
    paramVarArgs.add(new ah(new Locale("", "ME").getDisplayCountry(), 382));
    paramVarArgs.add(new ah(new Locale("", "MS").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "MA").getDisplayCountry(), 212));
    paramVarArgs.add(new ah(new Locale("", "MZ").getDisplayCountry(), 258));
    paramVarArgs.add(new ah(new Locale("", "MM").getDisplayCountry(), 95));
    paramVarArgs.add(new ah(new Locale("", "NA").getDisplayCountry(), 264));
    paramVarArgs.add(new ah(new Locale("", "NR").getDisplayCountry(), 674));
    paramVarArgs.add(new ah(new Locale("", "NP").getDisplayCountry(), 977));
    paramVarArgs.add(new ah(new Locale("", "NL").getDisplayCountry(), 31));
    paramVarArgs.add(new ah(new Locale("", "NC").getDisplayCountry(), 687));
    paramVarArgs.add(new ah(new Locale("", "NZ").getDisplayCountry(), 64));
    paramVarArgs.add(new ah(new Locale("", "NI").getDisplayCountry(), 505));
    paramVarArgs.add(new ah(new Locale("", "NE").getDisplayCountry(), 227));
    paramVarArgs.add(new ah(new Locale("", "NG").getDisplayCountry(), 234));
    paramVarArgs.add(new ah(new Locale("", "NU").getDisplayCountry(), 683));
    paramVarArgs.add(new ah(new Locale("", "NF").getDisplayCountry(), 672));
    paramVarArgs.add(new ah(new Locale("", "KP").getDisplayCountry(), 850));
    paramVarArgs.add(new ah(new Locale("", "MP").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "NO").getDisplayCountry(), 47));
    paramVarArgs.add(new ah(new Locale("", "OM").getDisplayCountry(), 968));
    paramVarArgs.add(new ah(new Locale("", "PK").getDisplayCountry(), 92));
    paramVarArgs.add(new ah(new Locale("", "PW").getDisplayCountry(), 680));
    paramVarArgs.add(new ah(new Locale("", "PS").getDisplayCountry(), 970));
    paramVarArgs.add(new ah(new Locale("", "PA").getDisplayCountry(), 507));
    paramVarArgs.add(new ah(new Locale("", "PG").getDisplayCountry(), 675));
    paramVarArgs.add(new ah(new Locale("", "PY").getDisplayCountry(), 595));
    paramVarArgs.add(new ah(new Locale("", "PE").getDisplayCountry(), 51));
    paramVarArgs.add(new ah(new Locale("", "PH").getDisplayCountry(), 63));
    paramVarArgs.add(new ah(new Locale("", "PL").getDisplayCountry(), 48));
    paramVarArgs.add(new ah(new Locale("", "PT").getDisplayCountry(), 351));
    paramVarArgs.add(new ah(new Locale("", "PR").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "QA").getDisplayCountry(), 974));
    paramVarArgs.add(new ah(new Locale("", "RE").getDisplayCountry(), 262));
    paramVarArgs.add(new ah(new Locale("", "RO").getDisplayCountry(), 40));
    paramVarArgs.add(new ah(new Locale("", "RU").getDisplayCountry(), 7));
    paramVarArgs.add(new ah(new Locale("", "RW").getDisplayCountry(), 250));
    paramVarArgs.add(new ah(new Locale("", "BL").getDisplayCountry(), 590));
    paramVarArgs.add(new ah(new Locale("", "SH").getDisplayCountry(), 290));
    paramVarArgs.add(new ah(new Locale("", "KN").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "LC").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "MF").getDisplayCountry(), 590));
    paramVarArgs.add(new ah(new Locale("", "PM").getDisplayCountry(), 508));
    paramVarArgs.add(new ah(new Locale("", "VC").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "WS").getDisplayCountry(), 685));
    paramVarArgs.add(new ah(new Locale("", "SM").getDisplayCountry(), 378));
    paramVarArgs.add(new ah(new Locale("", "ST").getDisplayCountry(), 239));
    paramVarArgs.add(new ah(new Locale("", "SA").getDisplayCountry(), 966));
    paramVarArgs.add(new ah(new Locale("", "SN").getDisplayCountry(), 221));
    paramVarArgs.add(new ah(new Locale("", "RS").getDisplayCountry(), 381));
    paramVarArgs.add(new ah(new Locale("", "SC").getDisplayCountry(), 248));
    paramVarArgs.add(new ah(new Locale("", "SL").getDisplayCountry(), 232));
    paramVarArgs.add(new ah(new Locale("", "SG").getDisplayCountry(), 65));
    paramVarArgs.add(new ah(new Locale("", "SX").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "SK").getDisplayCountry(), 421));
    paramVarArgs.add(new ah(new Locale("", "SI").getDisplayCountry(), 386));
    paramVarArgs.add(new ah(new Locale("", "SB").getDisplayCountry(), 677));
    paramVarArgs.add(new ah(new Locale("", "SO").getDisplayCountry(), 252));
    paramVarArgs.add(new ah(new Locale("", "ZA").getDisplayCountry(), 27));
    paramVarArgs.add(new ah(new Locale("", "GS").getDisplayCountry(), 500));
    paramVarArgs.add(new ah(new Locale("", "KR").getDisplayCountry(), 82));
    paramVarArgs.add(new ah(new Locale("", "SS").getDisplayCountry(), 211));
    paramVarArgs.add(new ah(new Locale("", "ES").getDisplayCountry(), 34));
    paramVarArgs.add(new ah(new Locale("", "LK").getDisplayCountry(), 94));
    paramVarArgs.add(new ah(new Locale("", "SD").getDisplayCountry(), 249));
    paramVarArgs.add(new ah(new Locale("", "SR").getDisplayCountry(), 597));
    paramVarArgs.add(new ah(new Locale("", "SJ").getDisplayCountry(), 47));
    paramVarArgs.add(new ah(new Locale("", "SZ").getDisplayCountry(), 268));
    paramVarArgs.add(new ah(new Locale("", "SE").getDisplayCountry(), 46));
    paramVarArgs.add(new ah(new Locale("", "CH").getDisplayCountry(), 41));
    paramVarArgs.add(new ah(new Locale("", "SY").getDisplayCountry(), 963));
    paramVarArgs.add(new ah(new Locale("", "TW").getDisplayCountry(), 886));
    paramVarArgs.add(new ah(new Locale("", "TJ").getDisplayCountry(), 992));
    paramVarArgs.add(new ah(new Locale("", "TZ").getDisplayCountry(), 255));
    paramVarArgs.add(new ah(new Locale("", "TH").getDisplayCountry(), 66));
    paramVarArgs.add(new ah(new Locale("", "TG").getDisplayCountry(), 228));
    paramVarArgs.add(new ah(new Locale("", "TK").getDisplayCountry(), 690));
    paramVarArgs.add(new ah(new Locale("", "TO").getDisplayCountry(), 676));
    paramVarArgs.add(new ah(new Locale("", "TT").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "TN").getDisplayCountry(), 216));
    paramVarArgs.add(new ah(new Locale("", "TR").getDisplayCountry(), 90));
    paramVarArgs.add(new ah(new Locale("", "TM").getDisplayCountry(), 993));
    paramVarArgs.add(new ah(new Locale("", "TC").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "TV").getDisplayCountry(), 688));
    paramVarArgs.add(new ah(new Locale("", "VI").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "UG").getDisplayCountry(), 256));
    paramVarArgs.add(new ah(new Locale("", "UA").getDisplayCountry(), 380));
    paramVarArgs.add(new ah(new Locale("", "AE").getDisplayCountry(), 971));
    paramVarArgs.add(new ah(new Locale("", "GB").getDisplayCountry(), 44));
    paramVarArgs.add(new ah(new Locale("", "US").getDisplayCountry(), 1));
    paramVarArgs.add(new ah(new Locale("", "UY").getDisplayCountry(), 598));
    paramVarArgs.add(new ah(new Locale("", "UZ").getDisplayCountry(), 998));
    paramVarArgs.add(new ah(new Locale("", "VU").getDisplayCountry(), 678));
    paramVarArgs.add(new ah(new Locale("", "VA").getDisplayCountry(), 379));
    paramVarArgs.add(new ah(new Locale("", "VE").getDisplayCountry(), 58));
    paramVarArgs.add(new ah(new Locale("", "VN").getDisplayCountry(), 84));
    paramVarArgs.add(new ah(new Locale("", "WF").getDisplayCountry(), 681));
    paramVarArgs.add(new ah(new Locale("", "EH").getDisplayCountry(), 212));
    paramVarArgs.add(new ah(new Locale("", "YE").getDisplayCountry(), 967));
    paramVarArgs.add(new ah(new Locale("", "ZM").getDisplayCountry(), 260));
    paramVarArgs.add(new ah(new Locale("", "ZW").getDisplayCountry(), 263));
    Collections.sort(paramVarArgs);
    return paramVarArgs;
  }
  
  protected void a(List<ah> paramList)
  {
    if (this.a != null) {
      this.a.a(paramList);
    }
  }
}


/* Location:              D:\Android\dex2jar-2.0\classes-dex2jar.jar!\com\digits\sdk\android\aj.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */