package com.digits.sdk.android;

import android.text.TextUtils;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

final class dq
{
  private final dx a;
  
  dq(dx paramdx)
  {
    this.a = paramdx;
  }
  
  private dg a(Map<String, Integer> paramMap)
  {
    String str = this.a.b();
    paramMap = a(str, paramMap);
    return new dg(a(this.a.a(), paramMap), str, paramMap);
  }
  
  private String a(String paramString1, String paramString2)
  {
    return paramString1.replaceFirst("^\\+?" + paramString2, "");
  }
  
  private String a(String paramString, Map<String, Integer> paramMap)
  {
    if (paramString == null) {
      return "";
    }
    paramString = (Integer)paramMap.get(paramString.toUpperCase(Locale.getDefault()));
    if (paramString == null) {
      return "";
    }
    return paramString.toString();
  }
  
  private String a(Map<Integer, List<String>> paramMap, String paramString)
  {
    paramMap = (List)paramMap.get(Integer.valueOf(paramString));
    if (paramMap != null) {
      return (String)paramMap.get(0);
    }
    return "US";
  }
  
  private String b(Map<Integer, List<String>> paramMap, String paramString)
  {
    paramString = paramString.replaceFirst("^\\+", "");
    int j = paramString.length();
    int i = 1;
    while ((i <= 3) && (i <= j))
    {
      String str = paramString.substring(0, i);
      if (paramMap.containsKey(Integer.valueOf(str))) {
        return str;
      }
      i += 1;
    }
    return "1";
  }
  
  private Map<Integer, List<String>> b()
  {
    HashMap localHashMap = new HashMap(286);
    ArrayList localArrayList = new ArrayList(25);
    localArrayList.add("US");
    localArrayList.add("AG");
    localArrayList.add("AI");
    localArrayList.add("AS");
    localArrayList.add("BB");
    localArrayList.add("BM");
    localArrayList.add("BS");
    localArrayList.add("CA");
    localArrayList.add("DM");
    localArrayList.add("DO");
    localArrayList.add("GD");
    localArrayList.add("GU");
    localArrayList.add("JM");
    localArrayList.add("KN");
    localArrayList.add("KY");
    localArrayList.add("LC");
    localArrayList.add("MP");
    localArrayList.add("MS");
    localArrayList.add("PR");
    localArrayList.add("SX");
    localArrayList.add("TC");
    localArrayList.add("TT");
    localArrayList.add("VC");
    localArrayList.add("VG");
    localArrayList.add("VI");
    localHashMap.put(Integer.valueOf(1), localArrayList);
    localArrayList = new ArrayList(2);
    localArrayList.add("RU");
    localArrayList.add("KZ");
    localHashMap.put(Integer.valueOf(7), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("EG");
    localHashMap.put(Integer.valueOf(20), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("ZA");
    localHashMap.put(Integer.valueOf(27), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("GR");
    localHashMap.put(Integer.valueOf(30), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("NL");
    localHashMap.put(Integer.valueOf(31), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BE");
    localHashMap.put(Integer.valueOf(32), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("FR");
    localHashMap.put(Integer.valueOf(33), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("ES");
    localHashMap.put(Integer.valueOf(34), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("HU");
    localHashMap.put(Integer.valueOf(36), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("IT");
    localHashMap.put(Integer.valueOf(39), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("RO");
    localHashMap.put(Integer.valueOf(40), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CH");
    localHashMap.put(Integer.valueOf(41), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("AT");
    localHashMap.put(Integer.valueOf(43), localArrayList);
    localArrayList = new ArrayList(4);
    localArrayList.add("GB");
    localArrayList.add("GG");
    localArrayList.add("IM");
    localArrayList.add("JE");
    localHashMap.put(Integer.valueOf(44), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("DK");
    localHashMap.put(Integer.valueOf(45), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SE");
    localHashMap.put(Integer.valueOf(46), localArrayList);
    localArrayList = new ArrayList(2);
    localArrayList.add("NO");
    localArrayList.add("SJ");
    localHashMap.put(Integer.valueOf(47), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("PL");
    localHashMap.put(Integer.valueOf(48), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("DE");
    localHashMap.put(Integer.valueOf(49), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("PE");
    localHashMap.put(Integer.valueOf(51), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MX");
    localHashMap.put(Integer.valueOf(52), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CU");
    localHashMap.put(Integer.valueOf(53), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("AR");
    localHashMap.put(Integer.valueOf(54), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BR");
    localHashMap.put(Integer.valueOf(55), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CL");
    localHashMap.put(Integer.valueOf(56), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CO");
    localHashMap.put(Integer.valueOf(57), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("VE");
    localHashMap.put(Integer.valueOf(58), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MY");
    localHashMap.put(Integer.valueOf(60), localArrayList);
    localArrayList = new ArrayList(3);
    localArrayList.add("AU");
    localArrayList.add("CC");
    localArrayList.add("CX");
    localHashMap.put(Integer.valueOf(61), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("ID");
    localHashMap.put(Integer.valueOf(62), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("PH");
    localHashMap.put(Integer.valueOf(63), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("NZ");
    localHashMap.put(Integer.valueOf(64), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SG");
    localHashMap.put(Integer.valueOf(65), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("TH");
    localHashMap.put(Integer.valueOf(66), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("JP");
    localHashMap.put(Integer.valueOf(81), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("KR");
    localHashMap.put(Integer.valueOf(82), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("VN");
    localHashMap.put(Integer.valueOf(84), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CN");
    localHashMap.put(Integer.valueOf(86), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("TR");
    localHashMap.put(Integer.valueOf(90), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("IN");
    localHashMap.put(Integer.valueOf(91), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("PK");
    localHashMap.put(Integer.valueOf(92), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("AF");
    localHashMap.put(Integer.valueOf(93), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("LK");
    localHashMap.put(Integer.valueOf(94), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MM");
    localHashMap.put(Integer.valueOf(95), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("IR");
    localHashMap.put(Integer.valueOf(98), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SS");
    localHashMap.put(Integer.valueOf(211), localArrayList);
    localArrayList = new ArrayList(2);
    localArrayList.add("MA");
    localArrayList.add("EH");
    localHashMap.put(Integer.valueOf(212), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("DZ");
    localHashMap.put(Integer.valueOf(213), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("TN");
    localHashMap.put(Integer.valueOf(216), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("LY");
    localHashMap.put(Integer.valueOf(218), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("GM");
    localHashMap.put(Integer.valueOf(220), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SN");
    localHashMap.put(Integer.valueOf(221), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MR");
    localHashMap.put(Integer.valueOf(222), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("ML");
    localHashMap.put(Integer.valueOf(223), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("GN");
    localHashMap.put(Integer.valueOf(224), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CI");
    localHashMap.put(Integer.valueOf(225), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BF");
    localHashMap.put(Integer.valueOf(226), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("NE");
    localHashMap.put(Integer.valueOf(227), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("TG");
    localHashMap.put(Integer.valueOf(228), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BJ");
    localHashMap.put(Integer.valueOf(229), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MU");
    localHashMap.put(Integer.valueOf(230), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("LR");
    localHashMap.put(Integer.valueOf(231), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SL");
    localHashMap.put(Integer.valueOf(232), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("GH");
    localHashMap.put(Integer.valueOf(233), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("NG");
    localHashMap.put(Integer.valueOf(234), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("TD");
    localHashMap.put(Integer.valueOf(235), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CF");
    localHashMap.put(Integer.valueOf(236), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CM");
    localHashMap.put(Integer.valueOf(237), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CV");
    localHashMap.put(Integer.valueOf(238), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("ST");
    localHashMap.put(Integer.valueOf(239), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("GQ");
    localHashMap.put(Integer.valueOf(240), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("GA");
    localHashMap.put(Integer.valueOf(241), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CG");
    localHashMap.put(Integer.valueOf(242), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CD");
    localHashMap.put(Integer.valueOf(243), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("AO");
    localHashMap.put(Integer.valueOf(244), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("GW");
    localHashMap.put(Integer.valueOf(245), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("IO");
    localHashMap.put(Integer.valueOf(246), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("AC");
    localHashMap.put(Integer.valueOf(247), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SC");
    localHashMap.put(Integer.valueOf(248), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SD");
    localHashMap.put(Integer.valueOf(249), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("RW");
    localHashMap.put(Integer.valueOf(250), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("ET");
    localHashMap.put(Integer.valueOf(251), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SO");
    localHashMap.put(Integer.valueOf(252), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("DJ");
    localHashMap.put(Integer.valueOf(253), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("KE");
    localHashMap.put(Integer.valueOf(254), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("TZ");
    localHashMap.put(Integer.valueOf(255), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("UG");
    localHashMap.put(Integer.valueOf(256), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BI");
    localHashMap.put(Integer.valueOf(257), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MZ");
    localHashMap.put(Integer.valueOf(258), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("ZM");
    localHashMap.put(Integer.valueOf(260), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MG");
    localHashMap.put(Integer.valueOf(261), localArrayList);
    localArrayList = new ArrayList(2);
    localArrayList.add("RE");
    localArrayList.add("YT");
    localHashMap.put(Integer.valueOf(262), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("ZW");
    localHashMap.put(Integer.valueOf(263), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("NA");
    localHashMap.put(Integer.valueOf(264), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MW");
    localHashMap.put(Integer.valueOf(265), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("LS");
    localHashMap.put(Integer.valueOf(266), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BW");
    localHashMap.put(Integer.valueOf(267), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SZ");
    localHashMap.put(Integer.valueOf(268), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("KM");
    localHashMap.put(Integer.valueOf(269), localArrayList);
    localArrayList = new ArrayList(2);
    localArrayList.add("SH");
    localArrayList.add("TA");
    localHashMap.put(Integer.valueOf(290), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("ER");
    localHashMap.put(Integer.valueOf(291), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("AW");
    localHashMap.put(Integer.valueOf(297), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("FO");
    localHashMap.put(Integer.valueOf(298), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("GL");
    localHashMap.put(Integer.valueOf(299), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("GI");
    localHashMap.put(Integer.valueOf(350), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("PT");
    localHashMap.put(Integer.valueOf(351), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("LU");
    localHashMap.put(Integer.valueOf(352), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("IE");
    localHashMap.put(Integer.valueOf(353), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("IS");
    localHashMap.put(Integer.valueOf(354), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("AL");
    localHashMap.put(Integer.valueOf(355), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MT");
    localHashMap.put(Integer.valueOf(356), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CY");
    localHashMap.put(Integer.valueOf(357), localArrayList);
    localArrayList = new ArrayList(2);
    localArrayList.add("FI");
    localArrayList.add("AX");
    localHashMap.put(Integer.valueOf(358), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BG");
    localHashMap.put(Integer.valueOf(359), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("LT");
    localHashMap.put(Integer.valueOf(370), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("LV");
    localHashMap.put(Integer.valueOf(371), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("EE");
    localHashMap.put(Integer.valueOf(372), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MD");
    localHashMap.put(Integer.valueOf(373), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("AM");
    localHashMap.put(Integer.valueOf(374), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BY");
    localHashMap.put(Integer.valueOf(375), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("AD");
    localHashMap.put(Integer.valueOf(376), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MC");
    localHashMap.put(Integer.valueOf(377), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SM");
    localHashMap.put(Integer.valueOf(378), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("VA");
    localHashMap.put(Integer.valueOf(379), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("UA");
    localHashMap.put(Integer.valueOf(380), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("RS");
    localHashMap.put(Integer.valueOf(381), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("ME");
    localHashMap.put(Integer.valueOf(382), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("HR");
    localHashMap.put(Integer.valueOf(385), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SI");
    localHashMap.put(Integer.valueOf(386), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BA");
    localHashMap.put(Integer.valueOf(387), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MK");
    localHashMap.put(Integer.valueOf(389), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CZ");
    localHashMap.put(Integer.valueOf(420), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SK");
    localHashMap.put(Integer.valueOf(421), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("LI");
    localHashMap.put(Integer.valueOf(423), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("FK");
    localHashMap.put(Integer.valueOf(500), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BZ");
    localHashMap.put(Integer.valueOf(501), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("GT");
    localHashMap.put(Integer.valueOf(502), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SV");
    localHashMap.put(Integer.valueOf(503), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("HN");
    localHashMap.put(Integer.valueOf(504), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("NI");
    localHashMap.put(Integer.valueOf(505), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CR");
    localHashMap.put(Integer.valueOf(506), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("PA");
    localHashMap.put(Integer.valueOf(507), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("PM");
    localHashMap.put(Integer.valueOf(508), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("HT");
    localHashMap.put(Integer.valueOf(509), localArrayList);
    localArrayList = new ArrayList(3);
    localArrayList.add("GP");
    localArrayList.add("BL");
    localArrayList.add("MF");
    localHashMap.put(Integer.valueOf(590), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BO");
    localHashMap.put(Integer.valueOf(591), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("GY");
    localHashMap.put(Integer.valueOf(592), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("EC");
    localHashMap.put(Integer.valueOf(593), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("GF");
    localHashMap.put(Integer.valueOf(594), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("PY");
    localHashMap.put(Integer.valueOf(595), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MQ");
    localHashMap.put(Integer.valueOf(596), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SR");
    localHashMap.put(Integer.valueOf(597), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("UY");
    localHashMap.put(Integer.valueOf(598), localArrayList);
    localArrayList = new ArrayList(2);
    localArrayList.add("CW");
    localArrayList.add("BQ");
    localHashMap.put(Integer.valueOf(599), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("TL");
    localHashMap.put(Integer.valueOf(670), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("NF");
    localHashMap.put(Integer.valueOf(672), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BN");
    localHashMap.put(Integer.valueOf(673), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("NR");
    localHashMap.put(Integer.valueOf(674), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("PG");
    localHashMap.put(Integer.valueOf(675), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("TO");
    localHashMap.put(Integer.valueOf(676), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SB");
    localHashMap.put(Integer.valueOf(677), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("VU");
    localHashMap.put(Integer.valueOf(678), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("FJ");
    localHashMap.put(Integer.valueOf(679), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("PW");
    localHashMap.put(Integer.valueOf(680), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("WF");
    localHashMap.put(Integer.valueOf(681), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("CK");
    localHashMap.put(Integer.valueOf(682), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("NU");
    localHashMap.put(Integer.valueOf(683), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("WS");
    localHashMap.put(Integer.valueOf(685), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("KI");
    localHashMap.put(Integer.valueOf(686), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("NC");
    localHashMap.put(Integer.valueOf(687), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("TV");
    localHashMap.put(Integer.valueOf(688), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("PF");
    localHashMap.put(Integer.valueOf(689), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("TK");
    localHashMap.put(Integer.valueOf(690), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("FM");
    localHashMap.put(Integer.valueOf(691), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MH");
    localHashMap.put(Integer.valueOf(692), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("001");
    localHashMap.put(Integer.valueOf(800), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("001");
    localHashMap.put(Integer.valueOf(808), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("KP");
    localHashMap.put(Integer.valueOf(850), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("HK");
    localHashMap.put(Integer.valueOf(852), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MO");
    localHashMap.put(Integer.valueOf(853), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("KH");
    localHashMap.put(Integer.valueOf(855), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("LA");
    localHashMap.put(Integer.valueOf(856), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("001");
    localHashMap.put(Integer.valueOf(870), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("001");
    localHashMap.put(Integer.valueOf(878), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BD");
    localHashMap.put(Integer.valueOf(880), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("001");
    localHashMap.put(Integer.valueOf(881), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("001");
    localHashMap.put(Integer.valueOf(882), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("001");
    localHashMap.put(Integer.valueOf(883), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("TW");
    localHashMap.put(Integer.valueOf(886), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("001");
    localHashMap.put(Integer.valueOf(888), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MV");
    localHashMap.put(Integer.valueOf(960), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("LB");
    localHashMap.put(Integer.valueOf(961), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("JO");
    localHashMap.put(Integer.valueOf(962), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SY");
    localHashMap.put(Integer.valueOf(963), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("IQ");
    localHashMap.put(Integer.valueOf(964), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("KW");
    localHashMap.put(Integer.valueOf(965), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("SA");
    localHashMap.put(Integer.valueOf(966), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("YE");
    localHashMap.put(Integer.valueOf(967), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("OM");
    localHashMap.put(Integer.valueOf(968), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("PS");
    localHashMap.put(Integer.valueOf(970), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("AE");
    localHashMap.put(Integer.valueOf(971), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("IL");
    localHashMap.put(Integer.valueOf(972), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BH");
    localHashMap.put(Integer.valueOf(973), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("QA");
    localHashMap.put(Integer.valueOf(974), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("BT");
    localHashMap.put(Integer.valueOf(975), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("MN");
    localHashMap.put(Integer.valueOf(976), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("NP");
    localHashMap.put(Integer.valueOf(977), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("001");
    localHashMap.put(Integer.valueOf(979), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("TJ");
    localHashMap.put(Integer.valueOf(992), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("TM");
    localHashMap.put(Integer.valueOf(993), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("AZ");
    localHashMap.put(Integer.valueOf(994), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("GE");
    localHashMap.put(Integer.valueOf(995), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("KG");
    localHashMap.put(Integer.valueOf(996), localArrayList);
    localArrayList = new ArrayList(1);
    localArrayList.add("UZ");
    localHashMap.put(Integer.valueOf(998), localArrayList);
    return localHashMap;
  }
  
  private Map<String, Integer> c()
  {
    HashMap localHashMap = new HashMap(291);
    localHashMap.put("AF", Integer.valueOf(93));
    localHashMap.put("AX", Integer.valueOf(358));
    localHashMap.put("AL", Integer.valueOf(355));
    localHashMap.put("DZ", Integer.valueOf(213));
    localHashMap.put("AS", Integer.valueOf(1));
    localHashMap.put("AD", Integer.valueOf(376));
    localHashMap.put("AO", Integer.valueOf(244));
    localHashMap.put("AI", Integer.valueOf(1));
    localHashMap.put("AG", Integer.valueOf(1));
    localHashMap.put("AR", Integer.valueOf(54));
    localHashMap.put("AM", Integer.valueOf(374));
    localHashMap.put("AW", Integer.valueOf(297));
    localHashMap.put("AC", Integer.valueOf(247));
    localHashMap.put("AU", Integer.valueOf(61));
    localHashMap.put("AT", Integer.valueOf(43));
    localHashMap.put("AZ", Integer.valueOf(994));
    localHashMap.put("BS", Integer.valueOf(1));
    localHashMap.put("BH", Integer.valueOf(973));
    localHashMap.put("BD", Integer.valueOf(880));
    localHashMap.put("BB", Integer.valueOf(1));
    localHashMap.put("BY", Integer.valueOf(375));
    localHashMap.put("BE", Integer.valueOf(32));
    localHashMap.put("BZ", Integer.valueOf(501));
    localHashMap.put("BJ", Integer.valueOf(229));
    localHashMap.put("BM", Integer.valueOf(1));
    localHashMap.put("BT", Integer.valueOf(975));
    localHashMap.put("BO", Integer.valueOf(591));
    localHashMap.put("BA", Integer.valueOf(387));
    localHashMap.put("BW", Integer.valueOf(267));
    localHashMap.put("BR", Integer.valueOf(55));
    localHashMap.put("IO", Integer.valueOf(246));
    localHashMap.put("VG", Integer.valueOf(1));
    localHashMap.put("BN", Integer.valueOf(673));
    localHashMap.put("BG", Integer.valueOf(359));
    localHashMap.put("BF", Integer.valueOf(226));
    localHashMap.put("BI", Integer.valueOf(257));
    localHashMap.put("KH", Integer.valueOf(855));
    localHashMap.put("CM", Integer.valueOf(237));
    localHashMap.put("CA", Integer.valueOf(1));
    localHashMap.put("CV", Integer.valueOf(238));
    localHashMap.put("BQ", Integer.valueOf(599));
    localHashMap.put("KY", Integer.valueOf(1));
    localHashMap.put("CF", Integer.valueOf(236));
    localHashMap.put("TD", Integer.valueOf(235));
    localHashMap.put("CL", Integer.valueOf(56));
    localHashMap.put("CN", Integer.valueOf(86));
    localHashMap.put("CX", Integer.valueOf(61));
    localHashMap.put("CC", Integer.valueOf(61));
    localHashMap.put("CO", Integer.valueOf(57));
    localHashMap.put("KM", Integer.valueOf(269));
    localHashMap.put("CD", Integer.valueOf(243));
    localHashMap.put("CG", Integer.valueOf(242));
    localHashMap.put("CK", Integer.valueOf(682));
    localHashMap.put("CR", Integer.valueOf(506));
    localHashMap.put("CI", Integer.valueOf(225));
    localHashMap.put("HR", Integer.valueOf(385));
    localHashMap.put("CU", Integer.valueOf(53));
    localHashMap.put("CW", Integer.valueOf(599));
    localHashMap.put("CY", Integer.valueOf(357));
    localHashMap.put("CZ", Integer.valueOf(420));
    localHashMap.put("DK", Integer.valueOf(45));
    localHashMap.put("DJ", Integer.valueOf(253));
    localHashMap.put("DM", Integer.valueOf(1));
    localHashMap.put("DO", Integer.valueOf(1));
    localHashMap.put("TL", Integer.valueOf(670));
    localHashMap.put("EC", Integer.valueOf(593));
    localHashMap.put("EG", Integer.valueOf(20));
    localHashMap.put("SV", Integer.valueOf(503));
    localHashMap.put("GQ", Integer.valueOf(240));
    localHashMap.put("ER", Integer.valueOf(291));
    localHashMap.put("EE", Integer.valueOf(372));
    localHashMap.put("ET", Integer.valueOf(251));
    localHashMap.put("FK", Integer.valueOf(500));
    localHashMap.put("FO", Integer.valueOf(298));
    localHashMap.put("FJ", Integer.valueOf(679));
    localHashMap.put("FI", Integer.valueOf(358));
    localHashMap.put("FR", Integer.valueOf(33));
    localHashMap.put("GF", Integer.valueOf(594));
    localHashMap.put("PF", Integer.valueOf(689));
    localHashMap.put("GA", Integer.valueOf(241));
    localHashMap.put("GM", Integer.valueOf(220));
    localHashMap.put("GE", Integer.valueOf(995));
    localHashMap.put("DE", Integer.valueOf(49));
    localHashMap.put("GH", Integer.valueOf(233));
    localHashMap.put("GI", Integer.valueOf(350));
    localHashMap.put("GR", Integer.valueOf(30));
    localHashMap.put("GL", Integer.valueOf(299));
    localHashMap.put("GD", Integer.valueOf(1));
    localHashMap.put("GP", Integer.valueOf(590));
    localHashMap.put("GU", Integer.valueOf(1));
    localHashMap.put("GT", Integer.valueOf(502));
    localHashMap.put("GG", Integer.valueOf(44));
    localHashMap.put("GN", Integer.valueOf(224));
    localHashMap.put("GW", Integer.valueOf(245));
    localHashMap.put("GY", Integer.valueOf(592));
    localHashMap.put("HT", Integer.valueOf(509));
    localHashMap.put("HM", Integer.valueOf(672));
    localHashMap.put("HN", Integer.valueOf(504));
    localHashMap.put("HK", Integer.valueOf(852));
    localHashMap.put("HU", Integer.valueOf(36));
    localHashMap.put("IS", Integer.valueOf(354));
    localHashMap.put("IN", Integer.valueOf(91));
    localHashMap.put("ID", Integer.valueOf(62));
    localHashMap.put("IR", Integer.valueOf(98));
    localHashMap.put("IQ", Integer.valueOf(964));
    localHashMap.put("IE", Integer.valueOf(353));
    localHashMap.put("IM", Integer.valueOf(44));
    localHashMap.put("IL", Integer.valueOf(972));
    localHashMap.put("IT", Integer.valueOf(39));
    localHashMap.put("JM", Integer.valueOf(1));
    localHashMap.put("JP", Integer.valueOf(81));
    localHashMap.put("JE", Integer.valueOf(44));
    localHashMap.put("JO", Integer.valueOf(962));
    localHashMap.put("KZ", Integer.valueOf(7));
    localHashMap.put("KE", Integer.valueOf(254));
    localHashMap.put("KI", Integer.valueOf(686));
    localHashMap.put("XK", Integer.valueOf(381));
    localHashMap.put("KW", Integer.valueOf(965));
    localHashMap.put("KG", Integer.valueOf(996));
    localHashMap.put("LA", Integer.valueOf(856));
    localHashMap.put("LV", Integer.valueOf(371));
    localHashMap.put("LB", Integer.valueOf(961));
    localHashMap.put("LS", Integer.valueOf(266));
    localHashMap.put("LR", Integer.valueOf(231));
    localHashMap.put("LY", Integer.valueOf(218));
    localHashMap.put("LI", Integer.valueOf(423));
    localHashMap.put("LT", Integer.valueOf(370));
    localHashMap.put("LU", Integer.valueOf(352));
    localHashMap.put("MO", Integer.valueOf(853));
    localHashMap.put("MK", Integer.valueOf(389));
    localHashMap.put("MG", Integer.valueOf(261));
    localHashMap.put("MW", Integer.valueOf(265));
    localHashMap.put("MY", Integer.valueOf(60));
    localHashMap.put("MV", Integer.valueOf(960));
    localHashMap.put("ML", Integer.valueOf(223));
    localHashMap.put("MT", Integer.valueOf(356));
    localHashMap.put("MH", Integer.valueOf(692));
    localHashMap.put("MQ", Integer.valueOf(596));
    localHashMap.put("MR", Integer.valueOf(222));
    localHashMap.put("MU", Integer.valueOf(230));
    localHashMap.put("YT", Integer.valueOf(262));
    localHashMap.put("MX", Integer.valueOf(52));
    localHashMap.put("FM", Integer.valueOf(691));
    localHashMap.put("MD", Integer.valueOf(373));
    localHashMap.put("MC", Integer.valueOf(377));
    localHashMap.put("MN", Integer.valueOf(976));
    localHashMap.put("ME", Integer.valueOf(382));
    localHashMap.put("MS", Integer.valueOf(1));
    localHashMap.put("MA", Integer.valueOf(212));
    localHashMap.put("MZ", Integer.valueOf(258));
    localHashMap.put("MM", Integer.valueOf(95));
    localHashMap.put("NA", Integer.valueOf(264));
    localHashMap.put("NR", Integer.valueOf(674));
    localHashMap.put("NP", Integer.valueOf(977));
    localHashMap.put("NL", Integer.valueOf(31));
    localHashMap.put("NC", Integer.valueOf(687));
    localHashMap.put("NZ", Integer.valueOf(64));
    localHashMap.put("NI", Integer.valueOf(505));
    localHashMap.put("NE", Integer.valueOf(227));
    localHashMap.put("NG", Integer.valueOf(234));
    localHashMap.put("NU", Integer.valueOf(683));
    localHashMap.put("NF", Integer.valueOf(672));
    localHashMap.put("KP", Integer.valueOf(850));
    localHashMap.put("MP", Integer.valueOf(1));
    localHashMap.put("NO", Integer.valueOf(47));
    localHashMap.put("OM", Integer.valueOf(968));
    localHashMap.put("PK", Integer.valueOf(92));
    localHashMap.put("PW", Integer.valueOf(680));
    localHashMap.put("PS", Integer.valueOf(970));
    localHashMap.put("PA", Integer.valueOf(507));
    localHashMap.put("PG", Integer.valueOf(675));
    localHashMap.put("PY", Integer.valueOf(595));
    localHashMap.put("PE", Integer.valueOf(51));
    localHashMap.put("PH", Integer.valueOf(63));
    localHashMap.put("PL", Integer.valueOf(48));
    localHashMap.put("PT", Integer.valueOf(351));
    localHashMap.put("PR", Integer.valueOf(1));
    localHashMap.put("QA", Integer.valueOf(974));
    localHashMap.put("RE", Integer.valueOf(262));
    localHashMap.put("RO", Integer.valueOf(40));
    localHashMap.put("RU", Integer.valueOf(7));
    localHashMap.put("RW", Integer.valueOf(250));
    localHashMap.put("BL", Integer.valueOf(590));
    localHashMap.put("SH", Integer.valueOf(290));
    localHashMap.put("KN", Integer.valueOf(1));
    localHashMap.put("LC", Integer.valueOf(1));
    localHashMap.put("MF", Integer.valueOf(590));
    localHashMap.put("PM", Integer.valueOf(508));
    localHashMap.put("VC", Integer.valueOf(1));
    localHashMap.put("WS", Integer.valueOf(685));
    localHashMap.put("SM", Integer.valueOf(378));
    localHashMap.put("ST", Integer.valueOf(239));
    localHashMap.put("SA", Integer.valueOf(966));
    localHashMap.put("SN", Integer.valueOf(221));
    localHashMap.put("RS", Integer.valueOf(381));
    localHashMap.put("SC", Integer.valueOf(248));
    localHashMap.put("SL", Integer.valueOf(232));
    localHashMap.put("SG", Integer.valueOf(65));
    localHashMap.put("SX", Integer.valueOf(1));
    localHashMap.put("SK", Integer.valueOf(421));
    localHashMap.put("SI", Integer.valueOf(386));
    localHashMap.put("SB", Integer.valueOf(677));
    localHashMap.put("SO", Integer.valueOf(252));
    localHashMap.put("ZA", Integer.valueOf(27));
    localHashMap.put("GS", Integer.valueOf(500));
    localHashMap.put("KR", Integer.valueOf(82));
    localHashMap.put("SS", Integer.valueOf(211));
    localHashMap.put("ES", Integer.valueOf(34));
    localHashMap.put("LK", Integer.valueOf(94));
    localHashMap.put("SD", Integer.valueOf(249));
    localHashMap.put("SR", Integer.valueOf(597));
    localHashMap.put("SJ", Integer.valueOf(47));
    localHashMap.put("SZ", Integer.valueOf(268));
    localHashMap.put("SE", Integer.valueOf(46));
    localHashMap.put("CH", Integer.valueOf(41));
    localHashMap.put("SY", Integer.valueOf(963));
    localHashMap.put("TW", Integer.valueOf(886));
    localHashMap.put("TJ", Integer.valueOf(992));
    localHashMap.put("TZ", Integer.valueOf(255));
    localHashMap.put("TH", Integer.valueOf(66));
    localHashMap.put("TG", Integer.valueOf(228));
    localHashMap.put("TK", Integer.valueOf(690));
    localHashMap.put("TO", Integer.valueOf(676));
    localHashMap.put("TT", Integer.valueOf(1));
    localHashMap.put("TN", Integer.valueOf(216));
    localHashMap.put("TR", Integer.valueOf(90));
    localHashMap.put("TM", Integer.valueOf(993));
    localHashMap.put("TC", Integer.valueOf(1));
    localHashMap.put("TV", Integer.valueOf(688));
    localHashMap.put("VI", Integer.valueOf(1));
    localHashMap.put("UG", Integer.valueOf(256));
    localHashMap.put("UA", Integer.valueOf(380));
    localHashMap.put("AE", Integer.valueOf(971));
    localHashMap.put("GB", Integer.valueOf(44));
    localHashMap.put("US", Integer.valueOf(1));
    localHashMap.put("UY", Integer.valueOf(598));
    localHashMap.put("UZ", Integer.valueOf(998));
    localHashMap.put("VU", Integer.valueOf(678));
    localHashMap.put("VA", Integer.valueOf(379));
    localHashMap.put("VE", Integer.valueOf(58));
    localHashMap.put("VN", Integer.valueOf(84));
    localHashMap.put("WF", Integer.valueOf(681));
    localHashMap.put("EH", Integer.valueOf(212));
    localHashMap.put("YE", Integer.valueOf(967));
    localHashMap.put("ZM", Integer.valueOf(260));
    localHashMap.put("ZW", Integer.valueOf(263));
    return localHashMap;
  }
  
  protected dg a()
  {
    if (this.a == null) {
      return dg.a();
    }
    return a(c());
  }
  
  protected dg a(String paramString)
  {
    if (TextUtils.isEmpty(paramString)) {
      return a();
    }
    String str2 = "1";
    String str1 = "US";
    Object localObject = paramString;
    if (paramString.startsWith("+"))
    {
      localObject = b();
      str2 = b((Map)localObject, paramString);
      str1 = a((Map)localObject, str2);
      localObject = a(paramString, str2);
    }
    return new dg((String)localObject, str1, str2);
  }
}


/* Location:              D:\Android\dex2jar-2.0\classes-dex2jar.jar!\com\digits\sdk\android\dq.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */